name: Download Postman Collection

on:
  workflow_dispatch:

jobs:
  download-collection-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Postman Collection and Environment Variables
        run: |
          POSTMAN_API_KEY=${{ secrets.POSTMAN_API_KEY_TEST }}
          COLLECTION_ID=${{ secrets.COLLECTION_ID_TEST }}
          POSTMAN_ENVIRONMENT_ID=${{ secrets.POSTMAN_API_KEY_TEST_ENV_VAR }} 

          curl -L "https://api.postman.com/collections/$COLLECTION_ID?access_key=$POSTMAN_API_KEY" -o api_response.json
          curl -L "https://api.postman.com/environments/$POSTMAN_ENVIRONMENT_ID" \
            -H "X-Api-Key: $POSTMAN_API_KEY" \
            -o postman_environment.json

      - name: Format JSON
        run: |
          jq . api_response.json > formatted_api_response.json
          mv formatted_api_response.json api_response.json

      - name: Commit and push JSON file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api_response.json
          git add postman_environment.json
          git commit -m "Add API response JSON"
          git pull
          git push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

  create-folder:
    needs: download-collection-postman
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull Latest Changes
        run: git pull origin test
        working-directory: ${{ github.workspace }}

      - name: Create Folder (if it doesn't exist)
        run: |
          if [ ! -d "request_test_folder" ]; then
            mkdir -p request_test_folder
            touch request_test_folder/.gitkeep  # Create a placeholder file if needed
          else
            echo "Folder already exists, skipping creation."
          fi
        working-directory: ${{ github.workspace }}

      - name: Commit and Push Changes (if there are changes)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Create request_test_folder"
            git push origin test  # Replace 'test' with your branch name
          else
            echo "No changes to commit, skipping."
          fi
        working-directory: ${{ github.workspace }}

  execute-python-script:
    needs: create-folder
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull Latest Changes
        run: git pull origin test
        working-directory: ${{ github.workspace }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Execute Python Script
        run: python main_file_folder_manager.py
        working-directory: ${{ github.workspace }}

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Execute main script"
          git push origin test
        working-directory: ${{ github.workspace }}