name: Save API Response to JSON

on:
  push:
    branches:
      - main

jobs:
  save_api_response:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          export COLLECTION_ID=${{ secrets.COLLECTION_ID_MAIN }}
          export POSTMAN_API_KEY=${{ secrets.POSTMAN_API_KEY_MAIN }}

      - name: Make API request and save response to JSON file
        run: |
          curl -L "https://api.postman.com/collections/$COLLECTION_ID?access_key=$POSTMAN_API_KEY" -o api_response.json

      - name: Commit and push JSON file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api_response.json
          git commit -m "Add API response JSON"
          git push