name: Update Postman Collection

on:
  push:
    branches:
      - main

jobs:
  update-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Newman
        run: npm install -g newman

      - name: Download Postman Collection
        run: |
          POSTMAN_API_KEY=${{ secrets.POSTMAN_API_KEY_MAIN }}
          COLLECTION_ID=${{ secrets.COLLECTION_ID_MAIN }}
          curl -L "https://api.postman.com/collections/$COLLECTION_ID" \
            -H "X-Api-Key: $POSTMAN_API_KEY" \
            -o collection.json

      - name: Convert Postman Collection to JSON
        run: |
          newman convert collection.json -o collection.json.postman
          mv collection.json.postman collection.json

      - name: Commit and Push to GitHub
        run: |
          git pull origin main
          git add collection.json
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update Postman Collection as JSON"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} --follow-tags --no-verify
        env:
          GH_PAT: ${{ secrets.GH_PAT }}