name: Download Postman Collection

on:
  workflow_dispatch:

jobs:
  download-collection-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Postman Collection
        run: |
          POSTMAN_API_KEY=${{ secrets.POSTMAN_API_KEY_TEST }}
          COLLECTION_ID=${{ secrets.COLLECTION_ID_TEST }}
          mkdir -p utils/api_json
          curl -L "https://api.postman.com/collections/$COLLECTION_ID?access_key=$POSTMAN_API_KEY" -o utils/api_json/api_response.json

      - name: Format JSON
        run: |
          cd utils/api_json
          jq . api_response.json > formatted_api_response.json
          mv formatted_api_response.json api_response.json

      - name: Commit and push JSON file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add utils/api_json/api_response.json
          git commit -m "Add API response JSON"
          git push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

  execute-python-script:
    needs: download-collection-postman
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Check if Folder Exists
        run: |
          if [ ! -d "request_test_folder" ]; then
            echo "Folder doesn't exist, creating it..."
            mkdir "request_test_folder"
          else
            echo "Folder already exists, skipping creation."
          fi

      - name: Commit and Push if Folder was Created
        if: ${{ steps.create-folder.outputs.changed == 'true' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "request_test_folder"
          git commit -m "Create folder if it doesn't exist"
          git push

      - name: Execute Python Script
        run: |
          python main_file_folder_manager.py