name: Manual Download Postman Collection

on:
  workflow_dispatch:

jobs:
  download-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Postman Collection
        run: |
          POSTMAN_API_KEY=${{ secrets.POSTMAN_API_KEY_MAIN }}
          COLLECTION_ID=${{ secrets.COLLECTION_ID_MAIN }}
          curl -L "https://api.postman.com/collections/$COLLECTION_ID?access_key=$POSTMAN_API_KEY" -o api_response.json

      - name: Commit and push JSON file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api_response.json
          git commit -m "Add API response JSON"
          git push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}