name: Update Postman Collection

on:
  push:
    branches:
      - main

jobs:
  update-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Newman
        run: npm install -g newman

      - name: Install newman-to-openapi
        run: npm install -g newman-to-openapi

      - name: Download Postman Collection
        run: |
          # Download your Postman collection as JSON using Postman API
          POSTMAN_API_KEY=${{ secrets.POSTMAN_API_KEY_MAIN }}
          COLLECTION_ID=${{ secrets.COLLECTION_ID_MAIN }}
          curl -L "https://api.postman.com/collections/$COLLECTION_ID" \
            -H "X-Api-Key: $POSTMAN_API_KEY" \
            -o collection.json

      - name: Convert Postman Collection to YAML
        run: newman-to-openapi convert -i collection.json -o collection.yaml

      - name: Commit and Push to GitHub
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add collection.yaml
          git commit -m "Update Postman Collection as YAML"
          git push origin main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
