name: Manual Download Postman Collection

on:
  workflow_dispatch:

jobs:
  download-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Postman Collection
        run: |
          POSTMAN_API_KEY=${{ secrets.POSTMAN_API_KEY_TEST }}
          COLLECTION_ID=${{ secrets.COLLECTION_ID_TEST }}
          curl -L "https://api.postman.com/collections/$COLLECTION_ID?access_key=$POSTMAN_API_KEY" -o api_response.json

      - name: Format JSON
        run: |
          jq . api_response.json > formatted_api_response.json
          mv formatted_api_response.json api_response.json
        shell: bash

      - name: Remove Trailing Whitespace from JSON
        run: |
          # Use jq to filter out trailing whitespace and empty lines
          jq -c . api_response.json | sed -e ':a' -e '/^\s*$/{$d;N;ba' -e '}' > formatted_api_response.json
          
          # Move the formatted file back to the original file
          mv formatted_api_response.json api_response.json
        shell: bash

      - name: Commit and push JSON file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api_response.json
          git commit -m "Add API response JSON"
          git push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Read and Separate Requests
        run: |
          # Install jq if it's not already available
          if ! command -v jq &> /dev/test/null; then
            sudo apt-get update
            sudo apt-get install jq -y
          fi

          jq -c '.requests[]' api_response.json | while read -r request; do
            request_name=$(echo "$request" | jq -r '.name')
            request_file="${request_name// /_}.json"
            echo "$request" > "$request_file"
          done
        shell: bash

      - name: Commit and Push Request Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.json
          git commit -m "Add individual request JSON files"
          git push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}