name: Download Postman Collection

on:
  push:
    branches:
      - main

jobs:
  download-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Postman Collection
        run: |
          POSTMAN_API_KEY=${{ secrets.POSTMAN_GITHUB_PAT }}
          COLLECTION_ID="YOUR_COLLECTION_ID" # Replace with your Postman collection ID
          curl -L "https://api.postman.com/collections/$COLLECTION_ID" \
            -H "X-Api-Key: $POSTMAN_API_KEY" \
            -o collection.json

      - name: Commit and Push to GitHub
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add collection.json
          git commit -m "Add Postman Collection"
          git push origin main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}