name: Postman Collections Sync

on:
  push:
    branches:
      - test

jobs:
  download-collection-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Latest Changes
        run: git pull origin test
        working-directory: ${{ github.workspace }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Execute Python Script
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_COLLECTION_KEY_TEST }}
          POSTMAN_API_KEY_ENV: ${{ secrets.POSTMAN_API_ENV_KEY }}
          POSTMAN_ENVIRONMENT_ID: ${{ secrets.POSTMAN_API_ENVIRONMENT_COLLECTION_ID }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_PASSPHRASE }}
        run: |
          python download_postman_env_var.py
        working-directory: ${{ github.workspace }}

      - name: Commit and push JSON file
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --local user.email "bassey@walter-group.com"
          git config --local user.name "EkeminiBassey1"
          git add .
          git commit -m "Postman environmental variables downloaded successfully"
          git push origin test

  create-folder:
    needs: download-collection-postman
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull Latest Changes
        run: git pull origin test
        working-directory: ${{ github.workspace }}

      - name: Create Folder (if it doesn't exist)
        run: |
          if [ ! -d "request_test_folder" ]; then
            mkdir -p request_test_folder
            touch request_test_folder/.gitkeep
          else
            echo "Folder already exists, skipping creation."
          fi
        working-directory: ${{ github.workspace }}

      - name: Commit and Push Changes (if there are changes)
        run: |
          git config --local user.email "bassey@walter-group.com"
          git config --local user.name "EkeminiBassey1"
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Create request test & backup collection folders"
            git push origin test
          else
            echo "No changes to commit, skipping."
          fi
        working-directory: ${{ github.workspace }}

  execute-python-script:
    needs: create-folder
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull Latest Changes
        run: git pull origin test
        working-directory: ${{ github.workspace }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Execute Python Script
        run: python main_file_folder_manager.py
        working-directory: ${{ github.workspace }}

      - name: Commit and Push Changes
        run: |
          git config --local user.email "bassey@walter-group.com"
          git config --local user.name "EkeminiBassey1"
          git add .
          git commit -m "Execute main script"
          git push origin test
        working-directory: ${{ github.workspace }}

  move_file:
    needs: execute-python-script
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull Latest Changes
        run: git pull origin test
        working-directory: ${{ github.workspace }}

      - name: Move File
        run: |
          mv postman_environment.json request_test_folder/
          git config --local user.email "bassey@walter-group.com"
          git config --local user.name "EkeminiBassey1"
          git add .
          git commit -m "Move postman_environment.json to request_test_folder"
          git push origin test
        working-directory: ${{ github.workspace }}

  delete-file:
    needs: encrypt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Latest Changes
        run: git pull origin test
        working-directory: ${{ github.workspace }}

      - name: Remove File
        run: |
          rm -f request_test_folder/postman_environment.json
          git config --local user.email "bassey@walter-group.com"
          git config --local user.name "EkeminiBassey1"
          git add request_test_folder/postman_environment.json
          git commit -m "Remove request_test_folder/postman_environment.json"
          git push origin test