name: Update Postman Collection

on:
  push:
    branches:
      - main

jobs:
  update-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Newman
        run: npm install -g newman

      - name: Install postman-to-openapi
        run: npm install -g postman-to-openapi

      - name: Download Postman Collection
        run: |
          # Download your Postman collection as JSON using Postman API
          POSTMAN_API_KEY=${{ secrets.POSTMAN_API_KEY_MAIN }}
          COLLECTION_ID=${{ secrets.COLLECTION_ID_MAIN }}
          curl -L "https://api.postman.com/collections/$COLLECTION_ID" \
            -H "X-Api-Key: $POSTMAN_API_KEY" \
            -o collection.json

      - name: Check if collection.yaml exists
        id: check-collection
        run: |
          if [ ! -f collection.yaml ]; then
            touch collection.yaml
          fi

      - name: Convert Postman Collection to YAML
        run: |
          # Replace the following command with the appropriate conversion command for your chosen package
          # Example: valid-package-name convert -i collection.json -o collection.yaml
          echo "Conversion command goes here"

      - name: Commit and Push to GitHub
        run: |
          git pull origin main
          git add collection.json
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add collection.yaml
          git commit -m "Update Postman Collection as YAML"
          # Use the PAT in the URL to authenticate
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} --follow-tags --no-verify
        env:
          GH_PAT: ${{ secrets.GH_PAT }}